### ISSUE TITLE
Describe where co-instructors should be/what they should do when they're not teaching

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#176] opened 2016-05-06 12:52 UTC
Add notes to `_episodes/20-practices.md` explaining where non-teaching instructors should be when someone else is at the front of the class; ditto helpers.

From @carpenterbennet at https://github.com/swcarpentry/website/issues/375:

Please add an item to the instructor's checklist that indicates that the not currently active instructors should sit at the back and not try to take an active role.  The helpers roles are different, and not currently active instructors should resist the urge to help unless there is clear need for it.  This is covered in the verbal portion of instructor training, but it didn't come across to me as a hard rule and expected behavior, but rather as one example of many.  It will help to prevent future confusion if it is added as a rule to the checklist.  At least for the workshop in which I was involved, the instructors were also not to act as helpers.

Please add to the item for lead instructors to be sure to go over with the other instructors prior to the workshop what the expected activity level should be for the not currently active instructors, and any other things that might help.  This will help alleviate any inadvertant misunderstandings, particularly for any new instructors.  This would also be the place to agree if some other arrangement among instructors could be agreed if the basic guidelines are to be deviated from.

I think this is particularly important when there are first-time or inexperienced instructors.  Software Carpentry teaching is possibly not like other teaching venues, and it is easy for people who have experience from other venues to bring with them habits that may not be appropriate in SWC.  Clearly set expectations are a good deal easier to meet.

I might make things more clear if the term 'coinstructor' is not used, as that is susceptible to misinterpretation.  Rather, it seems, instructors 'take turns' from one lesson to the next.

**Comment by anelda** [comment] 2016-05-19 14:39
In the workshops that we've run so far, the non-teaching instructor becomes a helper. It works really well as it shows the team spirit and it helped instructors to get to know their audience better and understand the things that they struggle with. I would prefer it if the non-teaching instructor didn't go to the back of the room and withdrew him/herself from what was happening in the class. 

I've often found it very re-insuring if I'm struggling to explain a concept well or if people are asking questions during a lesson that I can't answer well, if the second instructor assisted me. It's fun to have a wingman/woman and the non-teaching instructor also learn lots during active observation etc.

**Comment by justbennet** [comment] 2016-05-19 14:54
Anelda, that is the way I prefer to work, too, but when I tried that, it was interpreted as challenging the instructor's authority and deemed unacceptable behavior.

I entered this item so that some 'standard' could be proposed but that could be, by mutual prior agreement be changed for any given workshop.  It was very uncomfortable to have my behavior, which was intended to be helpful and collaborative interpreted in a bad way.

I would like to prevent someone else's well-intentioned helpfulness from being misinterpreted.  I would also like to prevent the withdrawing behavior from being misinterpreted as disinterest and disengagement, if that is not how it is intended.  There seems to be plenty of room for behavioral misinterpretation, boy howdy!

A checklist of expected roles/behavior as part of the operating procedures seemed a reasonable suggestion.

**Comment by anelda** [comment] 2016-05-19 15:01
Hi, yes, you're quite right. I appreciate active observation (if we can call it that) from my co-instructor, but I remember conversations about this on other SWC channels as well, where people have discussed this very issue. Some non-teaching instructors may probably also want to take over the lessons, especially if the instructor is very new. But I would not like it if we said the non-teaching instructor should sit in the back of the room. I think this is something that then should be discussed during instructor training... How to work together in the classroom? Very good point to raise I think. Thanks!

**Comment by karinlag** [comment] 2016-05-19 18:16
In my experience, the non-teaching instructor has done two things when not teaching:

1. act as a normal standard helper.
2. when asked in by the teaching instructor, helped out, explained stuff etc.

I.e. the non-teaching instructor is doing what I'd call active observation, but only steps in if the other person actually asks for it.

I have personally also on a couple of occasions approached the teaching instructor in periods where there was a lull (waiting for a challenge or similar thing) to ask if they are going to mention something and/or tipped them off about something. However, I have always done that in such a way that that was only directed to the instructor, so that that person could choose to act on what I said.

**Comment by ErinBecker** [comment] 2016-05-20 15:40
A lot of really good discussion here. Since there seem to be strongly held
views (and some good reasons) on both sides of the aisle, I'm wondering
whether the best guideline to give might not be "talk with your
co-instructors before-hand and decide what the non-teaching instructors
should be doing." We could then give some guidelines for either scenario -
e.g. if they decide that the non-teaching instructor should be acting as a
helper, set specific guidelines about how not to interfere with teaching,
what the appropriate way to contact the teaching instructor to communicate
issues, etc. If they decide the non-teaching instructor should be hands-off
- establish what they should be doing during that time - maybe compiling
notes to share with the other instructor(s) afterwards about things that
went really well or not so well.

For the record, the current version of the instructor training materials
strongly imply that the non-teaching instructor should act as a helper:

"The helpers and the instructor who isn’t teaching the particular episode
should keep an eye out for learners who are falling behind and intervene
early so that they don’t become frustrated and give up."


On Thu, May 19, 2016 at 11:18 AM, karinlag <notifications@github.com> wrote:

> In my experience, the non-teaching instructor has done two things when not
> teaching:
>
>    1. act as a normal standard helper.
>    2. when asked in by the teaching instructor, helped out, explained
>    stuff etc.
>
> I.e. the non-teaching instructor is doing what I'd call active
> observation, but only steps in if the other person actually asks for it.
>
> I have personally also on a couple of occasions approached the teaching
> instructor in periods where there was a lull (waiting for a challenge or
> similar thing) to ask if they are going to mention something and/or tipped
> them off about something. However, I have always done that in such a way
> that that was only directed to the instructor, so that that person could
> choose to act on what I said.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/instructor-training/issues/176#issuecomment-220408506>
>



-- 
*Erin Becker*, PhD
Data Carpentry, Associate Director
http://www.datacarpentry.org/
Research Associate, MMG Dept., UC Davis

**Comment by ErinBecker** [comment] 2017-02-28 22:12
Can I get a quick thumbs up, thumbs down on incorporating co-instructor guidelines somewhere and if so, where? The structure of the materials have changed a bit since this was proposed and I want to make sure this info goes in the best place. 

Will be closed 3/14 if no activity.

**Comment by lexnederbragt** [comment] 2017-03-01 10:16
+1, and I think it should go into the "Carpentry Teaching Practices" episode.

**Comment by justbennet** [comment] 2017-03-01 15:31
This will likely be different for each workshop and each set of instructors, and I don't think there is only one possible configuration or set of recommendations.  The one place where it should definitely be mentioned is at

    https://software-carpentry.org/checklists/lead/

It may belong as a supplement to the fourth bullet, which read

> With the other instructors, decide what content to cover, what the schedule will be, and who will teach what. This usually takes a few iterations, so don't leave it until the last minute.

at the time of this post.

I think the main thing is to encourage all the instructors to talk to each other before the workshop, whether in person or via some sort of video, but not just by e-mail or text.  If the role of coinstructor is meant to be real and formalized, then perhaps it deserves a checklist or some sort of page of its own, perhaps with some recommendations what is expected if there is little or no communication with the other instructors in advance of the class.  People come to teaching SWC from a lot of backgrounds -- some with a good deal of academic teaching experience, some with more tutoring/workshop experience -- and discussing ahead of time what will be covered, how, and by whom will help everyone do better and enjoy it more.

This topic does need to be mentioned in the training, as Lex pointed out, but it should be mentioned as part of the prep for workshops each time, as the people will change each time, and this is really more a personal thing among the specific instructors.

    https://software-carpentry.org/blog/2016/08/workshop-resources.html

That's really a helpful list, and all the materials for preparing a workshop should be reviewed and distributed to instructors prior to each workshop.

**Comment by karinlag** [comment] 2017-03-02 18:37
+1 to incorporating talk to your fellow instructors before teaching into the checklist, and to incorporating discussion of non-teaching teacher behavior in that. Also, this should be discussed in instructor training.

As pointed out by @justbennet's examples, we all expect things of people, and it is never a bad thing to get those expectations clarified so that everybody's onboard with things.

**Comment by ChristinaLK** [comment] 2017-03-07 18:14
+1 to adding to the checklist as suggested by @justbennet 
+1 to adding something about this to the instructor-training materials per @lexnederbragt's suggestion.

**Comment by ErinBecker** [comment] 2017-08-16 17:55
Closing based on duplication here: https://github.com/ErinBecker/instructor-training-reorg/issues/86

**Closed by ErinBecker** 2017-08-16 17:55 UTC
Labels: instructor-notes
